CREATE SEQUENCE ORDER_SEQ START WITH 1000 INCREMENT BY 1;
CREATE SEQUENCE ORDER_ITEM_SEQ START WITH 1000 INCREMENT BY 1;
-- ORDER
CREATE TABLE "order" (
ID INTEGER,
ORDER_STATUS_ID SMALLINT,
CUSTOMER_NAME VARCHAR(64),
CUSTOMER_PHONE VARCHAR(24),
CUSTOMER_COMMENT VARCHAR(128));
ALTER TABLE "order" ADD CONSTRAINT ORDER_ID_PK PRIMARY KEY (ID);
CREATE INDEX ORDER_PK_IDX ON "order"(ID);
-- ORDER ITEM
CREATE TABLE ORDER_ITEM (
ID INTEGER,
ORDER_ID INTEGER,
ITEM_NAME VARCHAR(64));
ALTER TABLE ORDER_ITEM ADD CONSTRAINT ORDER_ITEM_ID_PK PRIMARY KEY (ID);
ALTER TABLE ORDER_ITEM ADD CONSTRAINT OI_O_FK FOREIGN KEY (ORDER_ID)
REFERENCES "order"(ID);
CREATE INDEX ORDER_ITEM_PK_IDX ON ORDER_ITEM(ID);
CREATE INDEX ORDER_ITEM_FK_IDX ON ORDER_ITEM(ORDER_ID);