-- ORDER
CREATE SEQUENCE ORDER_SEQ START WITH 1000 INCREMENT BY 1;
CREATE TABLE "order"
(
    ID INTEGER,
    ORDER_STATUS_ID SMALLINT,
    PATIENT_ID INTEGER,
    CUSTOMER_COMMENT VARCHAR(128)
);
ALTER TABLE "order" ADD CONSTRAINT ORDER_ID_PK PRIMARY KEY (ID);
CREATE INDEX ORDER_PK_IDX ON "order"(ID);

-- ORDER ITEM
CREATE SEQUENCE ORDER_ITEM_SEQ START WITH 1000 INCREMENT BY 1;
CREATE TABLE ORDER_ITEM
(
    ID INTEGER,
    ORDER_ID INTEGER,
    ITEM_NAME VARCHAR(64)
);
ALTER TABLE ORDER_ITEM ADD CONSTRAINT ORDER_ITEM_ID_PK PRIMARY KEY (ID);
ALTER TABLE ORDER_ITEM ADD CONSTRAINT OI_O_FK FOREIGN KEY (ORDER_ID)
REFERENCES "order"(ID);
CREATE INDEX ORDER_ITEM_PK_IDX ON ORDER_ITEM(ID);
CREATE INDEX ORDER_ITEM_FK_IDX ON ORDER_ITEM(ORDER_ID);

-- SESSION
CREATE SEQUENCE SESSION_SEQ INCREMENT BY 1;
CREATE TABLE "session"
(
    ID INTEGER PRIMARY KEY,
    SESSION_ID VARCHAR(24),
    START_TIME TIMESTAMP,
    TIMEOUT_MINUTES INTEGER
);
ALTER TABLE "session" ADD CONSTRAINT session_id_unique UNIQUE (SESSION_ID)